# Generated by Django 5.2.6 on 2025-10-14 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['title'], 'verbose_name': 'Career', 'verbose_name_plural': 'Careers'},
        ),
        migrations.RemoveField(
            model_name='career',
            name='position',
        ),
        migrations.AddField(
            model_name='career',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='career',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='industries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='career',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
