# Generated by Django 5.2.6 on 2025-09-18 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=25, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('academic_year', models.CharField(blank=True, choices=[('highschool_freshman', 'Highschool Freshman'), ('highschool_sophomore', 'Highschool Sophomore'), ('highschool_junior', 'Highschool Junior'), ('highschool_senior', 'Highschool Senior'), ('college_freshman', 'College Freshman'), ('college_sophomore', 'College Sophomore'), ('college_junior', 'College Junior'), ('college_senior', 'College Senior'), ('graduate', 'Graduate Student'), ('alumni', 'Alumni')], max_length=20, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('personal_interests', models.JSONField(blank=True, default=list, help_text='List of your personal interests')),
                ('career_goals', models.TextField(blank=True, help_text='What are your career aspirations?')),
                ('clubs_interest', models.JSONField(blank=True, default=list, help_text='List of your clubs you want to join')),
                ('clubs_user_is_a_part_of', models.JSONField(blank=True, default=list, help_text='List of your clubs you are a part of or were a part of')),
                ('skills', models.JSONField(blank=True, default=list, help_text='Your current skills')),
                ('work_experience', models.TextField(blank=True, help_text='Brief description of work experience')),
                ('preferred_industries', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('preferred_positions', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('preferred_title', models.JSONField(blank=True, default=list)),
                ('preferred_company', models.JSONField(blank=True, default=list)),
                ('college', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.user')),
            ],
        ),
    ]
