# Generated by Django 5.2.6 on 2025-10-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_searching',
            field=models.BooleanField(default=True, help_text='Indicates whether the user is currently exploring colleges.'),
        ),
    ]
