# Generated by Django 5.2.6 on 2025-10-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_is_searching'),
        ('colleges', '0002_course_degreerequirementcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('avg_salary', models.IntegerField(blank=True, null=True)),
                ('top_skills', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='unique_user_major',
        ),
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='gpa_range',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='clubs_interest',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_searching',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='major',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_title',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='majors',
            field=models.ManyToManyField(blank=True, related_name='major_students', to='colleges.major'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='minors',
            field=models.ManyToManyField(blank=True, related_name='minor_students', to='colleges.major'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_phase',
            field=models.CharField(choices=[('EX', 'Explorer'), ('PL', 'Planner'), ('AD', 'Advancer'), ('LA', 'Launcher')], default='EX', max_length=2),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='career_goals',
        ),
        migrations.AddField(
            model_name='careerpath',
            name='related_interests',
            field=models.ManyToManyField(blank=True, to='accounts.interest'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_students', to='accounts.interest'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_goals',
            field=models.ManyToManyField(blank=True, related_name='students', to='accounts.careerpath'),
        ),
    ]
