# Generated by Django 5.2.6 on 2025-10-30 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_options_rename_name_course_title_and_more'),
        ('careers', '0002_alter_career_options_remove_career_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('PROJECT', 'Project'), ('CERT', 'Certification'), ('MILESTONE', 'Milestone'), ('INTERNSHIP', 'Internship'), ('COMPETITION', 'Competition')], default='PROJECT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('skills_gained', models.TextField(blank=True, help_text='Comma-separated list of skills')),
                ('estimated_hours', models.PositiveIntegerField(blank=True, help_text='Estimated hours to complete', null=True)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('resource_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_careers', models.ManyToManyField(blank=True, related_name='portfolio_items', to='careers.career')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['difficulty_level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Percentage complete (0-100)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_checklists', to='accounts.portfolioitem')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'User Checklist Item',
                'verbose_name_plural': 'User Checklist Items',
                'ordering': ['-priority', '-added_at'],
                'unique_together': {('user_profile', 'portfolio_item')},
            },
        ),
    ]
