# Generated by Django 5.2.6 on 2025-11-19 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_portfolioitem_userchecklist"),
        ("careers", "0002_alter_career_options_remove_career_position_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this plan (e.g., 'Plan A: Software Engineer')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Why you're interested in this career path",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True,
                        help_text="When do you want to achieve this career goal?",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this plan currently active?"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this your primary career plan?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_career",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_plans",
                        to="careers.career",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_plans",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Career Plan",
                "verbose_name_plural": "Career Plans",
                "ordering": ["-is_primary", "-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_title",
                    models.CharField(
                        blank=True, help_text="Custom milestone title", max_length=200
                    ),
                ),
                (
                    "custom_description",
                    models.TextField(
                        blank=True, help_text="Custom milestone description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                (
                    "target_semester",
                    models.CharField(
                        blank=True,
                        help_text="When to complete this (e.g., 'Fall 2025')",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5, help_text="Priority 1-10, higher is more important"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "career_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_items",
                        to="accounts.careerplan",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Course to take",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.course",
                    ),
                ),
                (
                    "portfolio_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Portfolio item (project, cert, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.portfolioitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Item",
                "verbose_name_plural": "Plan Items",
                "ordering": ["-priority", "added_at"],
            },
        ),
    ]
