# Generated by Django 5.2.6 on 2025-12-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_careerplan_planitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='academic_year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=10),
        ),
    ]
