# Generated by Django 5.2.6 on 2025-09-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=50, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
