# Generated by Django 5.2.6 on 2025-10-14 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('credits', models.DecimalField(decimal_places=1, default=3.0, max_digits=4)),
            ],
            options={
                'ordering': ['subject', 'number'],
                'unique_together': {('subject', 'number')},
            },
        ),
        migrations.CreateModel(
            name='DegreeRequirementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_credits', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_categories', to='colleges.major')),
            ],
            options={
                'ordering': ['major__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DegreeRequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='colleges.degreerequirementcategory')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.course')),
            ],
        ),
    ]
