# Generated by Django 5.2.6 on 2025-10-14 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_course_degreerequirementcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['college_name']},
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(blank=True, help_text='Optional link to a related major', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='colleges.major'),
        ),
        migrations.AlterField(
            model_name='degreerequirementitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_requirements', to='colleges.course'),
        ),
    ]
