# Generated by Django 5.2.6 on 2025-10-14 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0003_alter_college_options_course_major_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.TextField(blank=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.college')),
            ],
            options={
                'ordering': ['subject', 'number'],
                'unique_together': {('subject', 'number', 'college')},
            },
        ),
        migrations.CreateModel(
            name='DegreeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_credits', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='colleges.major')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.degreecategory')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='catalog.course')),
            ],
        ),
    ]
