# Generated by Django 5.2.6 on 2025-09-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Traject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
