# Generated by Django 5.2.6 on 2025-10-14 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_careerpath_interest_and_more'),
        ('colleges', '0002_course_degreerequirementcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='career_goals',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='majors',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_phase',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='clubs_interest',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_students', to='colleges.major'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='minors',
            field=models.ManyToManyField(blank=True, help_text='Optional secondary areas of study', related_name='minor_students', to='colleges.major'),
        ),
        migrations.DeleteModel(
            name='CareerPath',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_goals',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
