# Generated by Django 5.2.6 on 2025-10-14 22:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_careerpath_club_course'),
        ('colleges', '0003_alter_college_options_course_major_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='club',
            name='related_interests',
        ),
        migrations.AddField(
            model_name='careerpath',
            name='related_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_paths', to='colleges.major'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='salary_range',
            field=models.CharField(blank=True, help_text='Example: $60k–$90k/year', max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Academic, Sports, Cultural, Tech, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default='000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='relevant_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='clubs_interest',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='clubs_user_is_a_part_of',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPA on a 4.0 scale.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='minors',
            field=models.ManyToManyField(blank=True, help_text='Optional secondary areas of study.', related_name='minor_students', to='colleges.major'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_interests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_company',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_industries',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_locations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_positions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
